// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJyi6spCe-DD5ixCtxRtlJEqb_poXvXWA',
    appId: '1:627687794150:web:0c60fdcd6b91478c6ee227',
    messagingSenderId: '627687794150',
    projectId: 'smaglator-8da8e',
    authDomain: 'smaglator-8da8e.firebaseapp.com',
    storageBucket: 'smaglator-8da8e.appspot.com',
    measurementId: 'G-Q4WRXQWDQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4RQ146m2bTjrBJdXMh4ha3KlsmybSA9s',
    appId: '1:627687794150:android:a68f012e8aa523dd6ee227',
    messagingSenderId: '627687794150',
    projectId: 'smaglator-8da8e',
    storageBucket: 'smaglator-8da8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhPLm-0doNDbnUE4HfieRI5ICSaAQnCS8',
    appId: '1:627687794150:ios:722fce231bb57e1f6ee227',
    messagingSenderId: '627687794150',
    projectId: 'smaglator-8da8e',
    storageBucket: 'smaglator-8da8e.appspot.com',
    iosClientId: '627687794150-coj9vu25c0t4r33uglpqbqaa7hpijbqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smaglatorWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhPLm-0doNDbnUE4HfieRI5ICSaAQnCS8',
    appId: '1:627687794150:ios:045fefbf835602576ee227',
    messagingSenderId: '627687794150',
    projectId: 'smaglator-8da8e',
    storageBucket: 'smaglator-8da8e.appspot.com',
    iosClientId: '627687794150-l8bb6p87a8up45e0e5tvtiumtnmule0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.smaglatorWeb.RunnerTests',
  );
}
